---
title: "Taxonomy"
---

When categorising data gaps for this project, we rely on a modified version of a taxonomy developed by [Climate Change AI](https://www.climatechange.ai/dev/datagaps/info#taxonomy-of-data-gaps). Note that any particular gap may span multiple categories, and the boundaries between them are not always clear cut.

| Category | Description | Example |
|----------------|-------------------------------|-------------------------|
| Data Access | Assuming desired data exists, can different parties access it? Is the process of gaining access cumbersome? | “Can X researcher reasonably get access to Y dataset?” |
| Data Linkage | Assuming desired data exists, has it been linked with other relevant data? | “Answering X question requires Y and Z data to be linked.” |
| Data Quality | Is available data of reliable quality? Is it representative of the population of interest? Is it correctly capturing a variable of interest? | “Are estimates of X variable in Y survey biased?” |
| Data Sharing | Assuming desired data exists, is it shared with key parties? | “X department has Y data, but do not share it with Z researcher.” |
| Miscellaneous | Other gaps that do not fit into defined categories. |  |
| Standardisation / Harmonisation | Is available data collected in a standard way across systems or geographies? Is data comparable across relevant factors? | “Do local authorities collect and report on X topic in the same way?” |
| Sufficiency | Is available data sufficient for specific purposes? Can it be used to answer specific questions of interest? | “Does X data source enable analysis of Y group at Z geographical level?” |
| Timeliness | Is desired data published or otherwise made available for use in a timely, practically useful manner? | “X dataset is published too many years after data collection.” |
| Wish | Is desired data not collected at all? If collected, is it collated in a useful way? | “X data on Y topic is not currently collected.” |

[Add a new data gap](https://airtable.com/appCGMtdXOaqhWh4y/pagmTyuvNXMeVZMMS/form){.btn .btn-quarto target="_blank"}
